### ISSUE TITLE
OTP: Bei Update Feld `otp_config` anlegen

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [yakamara/redaxo_community#494]
**ErrorException:** Undefined array key "otp_config"
**File:** src\addons\yform\plugins\manager\lib\yform\manager\dataset.php
**Line:** 290

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                           | Line     |
| -------------------------------------------- | -------------------------------------------------------------- | -------- |
| rex_error_handler::handleError               | src\addons\yform\plugins\manager\lib\yform\manager\dataset.php | 290      |
| rex_yform_manager_dataset->getValue          | src\addons\ycom\plugins\auth\lib\otp\password_config.php       | 30       |
| rex_ycom_otp_password_config::forUser        | src\addons\ycom\plugins\auth\lib\otp\password_config.php       | 25       |
| rex_ycom_otp_password_config::forCurrentUser | src\addons\ycom\plugins\auth\lib\injections\otp.php            | 31       |
| rex_ycom_injection_otp->getRewrite           | src\addons\ycom\plugins\auth\lib\ycom_auth.php                 | 129      |
| rex_ycom_auth::init                          | src\addons\ycom\plugins\auth\boot.php                          | 21       |
| rex_package::{closure}                       | src\core\lib\extension.php                                     | 52       |
| rex_extension::{closure}                     | src\core\lib\util\timer.php                                    | 62       |
| rex_timer::measure                           | src\core\lib\extension.php                                     | 42       |
| rex_extension::registerPoint                 | src\addons\debug\lib\extensions\extension_debug.php            | 21       |
| rex_extension_debug::registerPoint           | src\core\lib\extension.php                                     | 37       |
| rex_extension::registerPoint                 | src\core\packages.php                                          | 31       |
| include_once                                 | src\core\frontend.php                                          | 12       |
| require                                      | src\core\boot.php                                              | 157      |
| require                                      | public\index.php                                               | 12       |

</details>
<details>
<summary>System report (REDAXO 5.17.1, PHP 8.3.7, MariaDB 10.11.9)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.17.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.3.7      |
|       OPcache | no         |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.11.9 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | WINNT          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.59  |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/129.0.0.0 |
|      Protocol | HTTP/1.1         |
|         HTTPS | yes              |

| Packages                 |                      |
| -----------------------: | :------------------- |
|             2factor_auth | 2.3                  |
|             accessdenied | 2.1.1                |
|                  adminer | 2.0.2                |
|              auto_delete | 1.0.2                |
|                   backup | 2.9.1                |
|                 be_style | 3.4.1                |
|      be_style/customizer | 3.3.1                |
|          be_style/redaxo | 3.4.1                |
|                  bloecks | 4.0.2                |
|         bloecks/cutncopy | 4.0.2                |
|                  cronjob | 2.11.0               |
|                    debug | 1.3.2                |
|                developer | 3.9.2                |
|                    feeds | 4.2.1                |
|               focuspoint | 4.2.3                |
|               iconpicker | 2.0.0                |
|                  install | 2.12.1               |
|           mailer_profile | 1.3.1                |
|              maintenance | 3.2.1                |
|                   mblock | 3.4.13               |
|            media_manager | 2.16.0               |
| media_manager_responsive | 1.1.7                |
|         media_negotiator | 4.0.4                |
|                mediapool | 2.14.0               |
|                 metainfo | 2.11.0               |
|                    mform | 8.0.4                |
|                milestone | 2.0.0                |
|               modulsuche | 1.4.1                |
|                    neues | 5.1.0-dev-2024-09-05 |
|                phpmailer | 2.13.1               |
|                 plus_bs5 | 0.1.5                |
|                  project | dev                  |
|          project_manager | 1.5.3                |
|   project_manager/client | 1.1.0                |
|                    qanda | 2.2.2                |
|                 redactor | 2.5.2                |
|                  rexstan | 1.0.191              |
|                search_it | 6.11.2               |
|          search_it/stats | 6.11.2               |
|       search_it_with_gpt | 1.1.0                |
|               sh_aktuell | 1.3.0                |
|         sh_kontaktstelle | 1.4.0                |
|                 speed_up | 1.4.0                |
|                    sprog | 1.5.1                |
|                    staff | 1.4.1                |
|               statistics | 3.1.0                |
|                structure | 2.17.1               |
|        structure/content | 2.17.1               |
|                    thumb | 1.0.0-dev-2024-09-09 |
|                 uploader | 2.4.2                |
|                      url | 2.1.0                |
|                    users | 2.11.0               |
|                   watson | 2.3.0                |
|          wenns_sein_muss | 5.1.0                |
|                     ycom | 4.3.0                |
|                ycom/auth | 4.3.0                |
|               ycom/group | 4.3.0                |
|            ycom_login_as | 2.0.0                |
|                  ydeploy | 2.0.2                |
|                    yform | 4.2.1                |
|              yform/email | 4.2.1                |
|            yform/manager | 4.2.1                |
|               yform/rest | 4.2.1                |
|              yform_field | 2.7.1                |
|            yform_geo_osm | 1.2.9                |
|          yform_rapidmail | 1.0.3                |
|    yform_spam_protection | 1.2.5                |
|          yform_usability | 2.1.4                |
|                     ymca | 2.2.0                |
|                 yrewrite | 2.10.0               |
|        yrewrite_metainfo | 2.1.1                |
|              zip_install | 1.5.3                |

</details>

**Comment by dergel** [comment]
wird hier gesetzt

https://github.com/yakamara/ycom/commit/454bbb8e64a20a5c3624643e10365f24b58cac55
