### ISSUE TITLE
Backend-Login und Frontend-Ansicht

### ISSUE THREAD

**Issue by DanielWeitenauer** [yakamara/redaxo_community#61]
Hi,
wenn man zwar in Redaxo nicht in der Community eingeloggt ist, kann man über die Webansicht der Artikel zwar die Artikel aufrufen, sieht aber nicht die entsprechenden Navigationspunkte. Bei größeren Community-Bereichen sieht man also evtl. gar keine Navigation. Kann man das nicht irgendwie vereinheitlichen?

**Comment by dergel** [comment]
Hallo,

leider wüsste ich nicht, wie man das machen könnte. Diese Seiten beinhalten ja eventuell userspezifische Informationen. Also z.B. eine Profilseite, oder Namen und Infos, oder spezielle Liste, für die man eingeloggt sein müsste. Im Moment sehe ich keinen Weg.. lg

**Comment by DanielWeitenauer** [comment]
Hi Jan,
danke für Deine Antwort. Ich hatte mich nur darüber gewundert, dass man die Artikel ja ansehen kann, wenn man sie sich über den "Webansicht" Link ansieht (also auch mit fehlender Userinfo), die Navigation aber gesperrt ist. Wäre man konsequent, müsste die Artikelansicht auch blockiert sein, wenn man nicht in der Community eingeloggt ist. Ich hatte gerade Kunden, die dachten, ihre Seite wäre kaputt. Aber ich denke ich werde das irgendwie im Template behandeln.
Viele Grüße,
Daniel
