### ISSUE TITLE
Tabelle: Community Kommentare

### ISSUE THREAD

**Issue by fw-thomas** [yakamara/redaxo_community#70]
Hallo zusammen,
wenn ich in der Tabelle einen Kommentar Sperre, durch Anklicken des Status Kästchen und speichere, wird mir auf der Webseite dieser dann als Gesperrt angezeigt.
Soweit so gut.

Nehme ich nun den Harken wieder raus und speichere es, bleibt dieser weiterhin gesperrt !!

Jemand eine Idee?

mfg
thomas

**Comment by fw-thomas** [comment]
Hallo zusammen,
wenn ich in der Tabelle einen Kommentar Sperre, durch Anklicken des Status Kästchen und speichere, wird mir auf der Webseite dieser dann als Gesperrt angezeigt.
Soweit so gut.

Nehme ich nun den Harken wieder raus und speichere es, bleibt dieser weiterhin gesperrt !!

Jemand eine Idee?

mfg
thomas

**Comment by tbaddade** [comment]
Schau mal ob sich der Wert in der DB nach dem Speichern tatsächlich ändert.

**Comment by fw-thomas** [comment]
Nabend,
ich habe einen Kommentar in Redaxo Tabelle: Community Kommentare, den Harken bei Status gesetzt, somit wurde er auf der Webseite als "Kommentare wurde gesperrt" angezeigt.
In der DB wurde der Status von 1 auf  " " << ohne eintrag gesetzt,.

Nehme ich nun den Harken wieder raus, so ändert sich nix.

Ich kann dann zwar über phpMyAdmin den Status manuell ändern, aber das ist wohl nicht Sinn der Sache.

mfg
thomas

**Comment by fw-thomas** [comment]
Guten Morgen,

ich habe zwar wenig Ahnung von Datenbanken, aber ist die Reihenfolge nicht Wichtig ??

![db-phpmyadmin](https://cloud.githubusercontent.com/assets/12305603/7930189/86418972-0906-11e5-978b-bdf178b13901.jpg)
![db-redaxo](https://cloud.githubusercontent.com/assets/12305603/7930190/86427ecc-0906-11e5-93c6-56953b61d6a1.jpg)

Was ich heute nochmal getestet habe, einen Kommentar geschrieben, über phpmyadmin den Status auf "0" gesetzt und dann in Redaxo geschaut, dort war Kein Harken bei Status in der Liste.
Habe ich den Harken gesetzt, so verschwindet die "0" aus dem phpmyadmin.

mfg
thomas

**Comment by dergel** [comment]
ich habe es mir nun endlich angesehen.. leider kann ich den fehler nicht finden - zumindest nicht im community addon..

kannst du mal prüfen ob du die aktuellste XForm hast ? Eventuell liegt es daran. und auch dort nachschauen was bei status steht (siehe dein 2. Screenshot - dort mal auf id=11 status editieren klicken)

der " " Wert ist falsch. da sollte 1 oder 0 drin stehen.

**Comment by fw-thomas** [comment]
Ich habe die Version .. 

AddOn: xform
Version: 4.12
Autor: Jan Kristinus
Hilfe: www.yakamara.de/tag/xform/


Der Wert " " wird eingetragen, sobald eine Manuelle änderung vorgenommen wird.
Ich habe es für mich erstmal so gelöst, das ich  einen direktlink in die SQL DB habe um dort den Wert "1" einzutragen und somit den Gästebuchbeitrag freigeben kann.

**Comment by fw-thomas** [comment]
Guten Morgen,
Ich habe Xform heute auf den Neusten Stand gebracht:
Hilfe für xform
AddOn: xform
Version: 4.9
Autor: Jan Kristinus

Und wieder einen Eintrag vorgenommen, Nun steht unter Status eine "0" ..
Allerdings unter Tabelle: Community Kommentare, kann ich nix erkennen, das dort der Status auf offline ist.. 

Wenn ich eine änderung vornehme, verschwindet aus der Datenbank die "0" und das Feld bleibt leer.
mfg
thomas

**Comment by fw-thomas** [comment]
habe ich den Beitrag in phpMyAdmin auf Status "1" gesetzt und gespeichert, nehmen dann noch eine Änderung dort vor, ändert sich der Status nicht.

Mach ich eine Änderung in Redaxo, verschwindet die "1"  auf ein Leeres Feld

**Comment by tbaddade** [comment]
Wie ist denn das Feld im XForm Tablemanager angelegt?

Im speziellen hier: `Werte (0,1) (nicht angeklickt,angeklickt)`

**Comment by fw-thomas** [comment]
Anbei die Info ..
![xform](https://cloud.githubusercontent.com/assets/12305603/8303333/794ed3ee-199d-11e5-9e38-8d123dd1ba49.jpg)

**Comment by fw-thomas** [comment]
ich habe in dieser Zeile eine änderung vorgenommen

https://github.com/yakamara/redaxo_community/blob/master/plugins/comment/classes/class.rex_com_comments.inc.php#L113

Den Wert habe ich von 1 auf 0 gesetzt, das die eingetragenen Beiträge erstmal Offline sind.
Das hat ja auch soweit geklappt .. 

Aber eine Freigabe kann ich durch Redaxo nicht machen .. Nur über phpMyAdmin machen ..

**Comment by tbaddade** [comment]
Trag mal bei **Werte** `0,1`ein. So wie es dort in Klammern steht.

**Comment by fw-thomas** [comment]
Hallo,
Habe dort den Wert "1" eingetragen und nun klappt das ganze dann auch .. 

Somit kann ich das hier abschließen ...
jetzt fehlt nur noch das ich eine Mail raussenden kann .. das ein neuer Beitrag gekommen ist ..

**Comment by tbaddade** [comment]
Du musst zwei Werte eintragen  `0,1`. Der erste Wert gilt, wenn die Checkbox nicht geklickt wurde. Der zweite wird gesetzt wenn diese geklickt wurde. Beide Werte mit Komma trennen, so wie es im label beschrieben ist.

**Comment by fw-thomas** [comment]
Würde so es gehen ??
https://github.com/yakamara/redaxo_community/blob/master/plugins/comment/classes/class.rex_com_comments.inc.php#L127

$xform->setActionField('db', array('rex_com_comment'));
$xform->setaction|db2email|Com-Kom_de| <<<<< z.B. so gehen???
$xform->setActionField('showtext', array('translate:com_comment_thankyourforentry', '<div class="comment-add-answer">', '</div>', 2));

**Comment by tbaddade** [comment]
Das hat nichts mehr mit den Speichern deiner Werte zu tun oder? Ist das obige Problem behoben?

Zu deiner Zeile nur so viel. Es fehlt eine E-Mail-Adresse.

Bitte beachte, dass es hier kein Forum ist.

**Comment by fw-thomas** [comment]
ja das Obrige Problem ist gelöst ..
