### ISSUE TITLE
Tabellendarstellung Backend zeigt keine Übersetzung 

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_community#72]
Hallo,

im Backend wird die Übersetzung für den Status nicht richtig angezeigt.
(Auch nicht beim editieren des Datensatzes)

LG
Oliver

![translate](https://cloud.githubusercontent.com/assets/330516/7749115/027ac002-ffcb-11e4-8135-5050b6ff6db8.jpg)

**Comment by tyrant88** [comment]
Hi, bei mir auch. Allerdings beim editieren des Datensatzes geht es.

**Comment by tbaddade** [comment]
Wurde hier bereits gefixed
https://github.com/yakamara/redaxo_xform/commit/4e8bf472cc078218ba9266e26da5e8f1ab81cb75

**Comment by tyrant88** [comment]
Danke für die prompte Bearbeitung!
