### ISSUE TITLE
Community Kommentare <> Mail Benarichtigung

### ISSUE THREAD

**Issue by fw-thomas** [yakamara/redaxo_community#74]
Hallo zusammen,

Ich würde gerne bei den Kommentare eine Mail bekommen, wenn ein Neuer Eintrag abgeschickt wurde.

Wie muss ich vorgehen?

mfg
thomas

**Comment by fw-thomas** [comment]
Hallo zusammen,

Ich würde gerne bei den Kommentare eine Mail bekommen, wenn ein Neuer Eintrag abgeschickt wurde.

Wie muss ich vorgehen?

**Comment by tbaddade** [comment]
Du könntest hier https://github.com/yakamara/redaxo_community/blob/master/plugins/comment/classes/class.rex_com_comments.inc.php#L127 ein weiteres ActionField notieren oder aber dich an diesen EP https://github.com/yakamara/redaxo_xform/blob/b28b307e76b78bc76001e41ede2bdfadbc0eacea/classes/action/class.xform.action_db.inc.php#L67 hängen.

Ich schließe auch das Issue, da es mehr ein Forenthema ist.
